import { createContext } from "react";

const GlobalContext = createContext({
	theme: "",
	setTheme: () => {},
	toggleTheme: () => {},
	accentColor: "",
	setAccentColor: () => {},
	handleAccentColor: () => {},
	networkStatus: "offline",
	setNetworkStatus: () => {},
	breakpoint: () => {},
	isLoading: "",
	setIsLoading: () => {},
	snack: {},
	setSnack: () => {},
	openSnackBar: false,
	setOpenSnackBar: () => {},
	isAuthenticated: "",
	setIsAuthenticated: () => {},
	user: undefined,
	setUser: () => {},
	updateUser: () => {},
	openSideBar: "",
	setOpenSideBar: () => {},
	toggleSideBar: () => {},
	sideBarLinks: [],
	setSideBarLinks: () => {},
	axiosInstance: undefined,
	events: [],
	setEvents: () => {},
	getAllEvents: () => {},
	addNewEvent: () => {},
	updateOneEvent: () => {},
	moveEventToTrash: () => {},
});

export default GlobalContext;
